config/routes.rb
AmoebaCircusRails::Application.routes.draw do
  resources :acts

  resources :amoebas do
    post 'split', on: :member
  end

end

app/models/act.rb
class Act < ActiveRecord::Base
  has_many :acts_amoebas
  has_many :amoebas, :through => :acts_amoebas
end

app/models/acts_amoeba.rb
class ActsAmoeba < ActiveRecord::Base
  belongs_to :act
  belongs_to :amoeba
end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  belongs_to :talent
  has_many :acts_amoebas
  has_many :acts, :through => :acts_amoebas

  def talent_name
    self.talent ? self.talent.name : "None"
  end

  def split
    Amoeba.create(:name => "#{name} C1", :generation => generation + 1, :talent => talent, :acts => acts)
    Amoeba.create(:name => "#{name} C2", :generation => generation + 1, :talent => talent, :acts => acts)
    self.destroy
  end

end

app/models/talent.rb
class Talent < ActiveRecord::Base
  has_many :amoebas
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts
  # GET /acts.json
  def index
    @acts = Act.all
  end

  # GET /acts/1
  # GET /acts/1.json
  def show
  end

  # GET /acts/new
  def new
    @act = Act.new
  end

  # GET /acts/1/edit
  def edit
  end

  # POST /acts
  # POST /acts.json
  def create
    @act = Act.new(act_params)

    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render action: 'show', status: :created, location: @act }
      else
        format.html { render action: 'new' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acts/1
  # PATCH/PUT /acts/1.json
  def update
    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_to @act, notice: 'Act was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act.destroy
    respond_to do |format|
      format.html { redirect_to acts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_act
      @act = Act.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def act_params
      params.require(:act).permit(:name, :date, :amoeba_ids => [])
    end
end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
  before_action :set_amoeba, only: [:show, :edit, :update, :destroy, :split]

  # GET /amoebas
  # GET /amoebas.json
  def index
    @amoebas = Amoeba.all
  end

  # GET /amoebas/1
  # GET /amoebas/1.json
  def show
  end

  # GET /amoebas/new
  def new
    @amoeba = Amoeba.new
  end

  # GET /amoebas/1/edit
  def edit
  end

  # POST /amoebas
  # POST /amoebas.json
  def create
    @amoeba = Amoeba.new(amoeba_params)

    respond_to do |format|
      if @amoeba.save
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully created.' }
        format.json { render action: 'show', status: :created, location: @amoeba }
      else
        format.html { render action: 'new' }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amoebas/1
  # PATCH/PUT /amoebas/1.json
  def update
    respond_to do |format|
      if @amoeba.update(amoeba_params)
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amoebas/1
  # DELETE /amoebas/1.json
  def destroy
    @amoeba.destroy
    respond_to do |format|
      format.html { redirect_to amoebas_url }
      format.json { head :no_content }
    end
  end

  def split
    @amoeba.split
    redirect_to amoebas_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amoeba
      @amoeba = Amoeba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amoeba_params
      params.require(:amoeba).permit(:name, :talent_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/amoebas_helper.rb
module AmoebasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
      <% @act.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<h1>Editing act</h1>

<%= render 'form' %>

<%= link_to 'Show', @act %> |
<%= link_to 'Back', acts_path %>

app/views/acts/index.html.erb
<h1>Listing acts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @acts.each do |act| %>
      <tr>
        <td><%= act.name %></td>
        <td><%= act.date %></td>
        <td><%= link_to 'Show', act %></td>
        <td><%= link_to 'Edit', edit_act_path(act) %></td>
        <td><%= link_to 'Destroy', act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Act', new_act_path %>

app/views/acts/new.html.erb
<h1>New act</h1>

<%= render 'form' %>

<%= link_to 'Back', acts_path %>

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @act.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @act.date %>
</p>

<p>
  <strong>Amoebas:</strong>
  <ul style="list-style-type:none;">
    <% @act.amoebas.each do |amoeba| %>
      <li><%= amoeba.name %>:<%= amoeba.talent_name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_act_path(@act) %> |
<%= link_to 'Back', acts_path %>

app/views/amoebas/_form.html.erb
<%= form_for(@amoeba) do |f| %>
  <% if @amoeba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amoeba.errors.count, "error") %> prohibited this amoeba from being saved:</h2>

      <ul>
      <% @amoeba.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :generation %><br>
    <%= f.number_field :generation %>
  </div>

  <div class="field">
    <%= f.label :talent %><br>
    <%= f.select :talent_id, options_from_collection_for_select(Talent.all, :id, :name, @amoeba.talent_id) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amoebas/edit.html.erb
<h1>Editing amoeba</h1>

<%= render 'form' %>

<%= link_to 'Show', @amoeba %> |
<%= link_to 'Back', amoebas_path %>

app/views/amoebas/index.html.erb
<h1>Listing amoebas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Generation</th>
      <th>Talent</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @amoebas.each do |amoeba| %>
      <tr>
        <td><%= amoeba.name %></td>
        <td><%= amoeba.generation %></td>
        <td><%= amoeba.talent_name %></td>
        <td><%= link_to 'Show', amoeba %></td>
        <td><%= link_to 'Edit', edit_amoeba_path(amoeba) %></td>
        <td><%= link_to 'Destroy', amoeba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amoeba', new_amoeba_path %>

app/views/amoebas/new.html.erb
<h1>New amoeba</h1>

<%= render 'form' %>

<%= link_to 'Back', amoebas_path %>

app/views/amoebas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @amoeba.name %>
</p>

<p>
  <strong>Generation:</strong>
  <%= @amoeba.generation %>
</p>

<p>
  <strong>Talent:</strong>
  <%= @amoeba.talent_name %>
</p>

<%= form_tag split_amoeba_path(@amoeba) do %>
  <%= submit_tag 'Split' %>
<% end %>

<%= link_to 'Edit', edit_amoeba_path(@amoeba) %> |
<%= link_to 'Back', amoebas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaCircusRails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>